# Generated by Django 4.2.3 on 2023-07-31 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cointoss',
            name='toss_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
